export const THEMES = [
  {
    id: "family",
    title: "我的家人",
    emoji: "👨‍👩‍👧‍👦",
    cover: "images/words/mama.jpg",
    words: [
      { id: "baba", text: "爸爸", aliases: ["爸爸", "爸", "爹爹", "爸爸爸爸", "巴巴", "baba", "papa", "baabaa", "daddy"] },
      { id: "mama", text: "媽媽", aliases: ["媽媽", "媽", "妈咪", "媽咪", "妈妈", "馬馬", "嫲嫲", "mama", "mommy", "maamaa"] },
      { id: "gege", text: "哥哥", aliases: ["哥哥", "哥", "gege", "gogo"] },
      { id: "didi", text: "弟弟", aliases: ["弟弟", "弟", "didi", "daidai"] },
      { id: "jiejie", text: "姐姐", aliases: ["姐姐", "姊姊", "姐", "姊", "姐姐姐姐", "jiejie", "zeze"] },
      { id: "meimei", text: "妹妹", aliases: ["妹妹", "妹", "meimei", "muimui"] },
      { id: "yeye", text: "爺爺", aliases: ["爺爺", "爷爷", "阿爺", "yeye", "jeje"] },
      { id: "nainai", text: "奶奶", aliases: ["奶奶", "嫲嫲", "阿嫲", "nainai", "naai"] },
    ],
  },
  {
    id: "body",
    title: "我的身體",
    emoji: "👀",
    cover: "images/words/yanjing.jpg",
    words: [
      { id: "yanjing", text: "眼睛", aliases: ["眼睛", "眼", "yanjing", "ngaan"] },
      { id: "erduo", text: "耳朵", aliases: ["耳朵", "耳", "erduo", "yee"] },
      { id: "bizi", text: "鼻子", aliases: ["鼻子", "鼻", "bizi", "bei"] },
      { id: "zuiba", text: "嘴巴", aliases: ["嘴巴", "口", "嘴", "zuiba", "zui"] },
      { id: "shou", text: "手", aliases: ["手", "小手", "雙手", "shou", "sau"] },
      { id: "jiao", text: "腳", aliases: ["腳", "脚", "小腳", "jiao", "geuk", "goek"] },
      { id: "tou", text: "頭", aliases: ["頭", "头", "tou", "tau"] },
      { id: "toufa", text: "頭髮", aliases: ["頭髮", "头发", "髮", "发", "toufa", "taufaat"] },
    ],
  },
  {
    id: "animals",
    title: "動物朋友",
    emoji: "🐱",
    cover: "images/words/mao.jpg",
    words: [
      { id: "mao", text: "貓", aliases: ["貓", "猫", "貓咪", "小猫", "貓咪貓", "mao", "maau", "miao", "cat"] },
      { id: "gou", text: "狗", aliases: ["狗", "小狗", "狗狗", "gou", "gau", "dog"] },
      { id: "yu", text: "魚", aliases: ["魚", "鱼", "小魚", "yu", "jyu", "fish"] },
      { id: "niao", text: "鳥", aliases: ["鳥", "鸟", "小鳥", "niao", "niu", "bird"] },
      { id: "tuzi", text: "兔子", aliases: ["兔子", "兔", "小兔", "兔兔", "tuzi", "touzi", "rabbit"] },
      { id: "daxiang", text: "大象", aliases: ["大象", "象", "daxiang", "zoeng"] },
      { id: "laohu", text: "老虎", aliases: ["老虎", "虎", "laohu", "loufu"] },
      { id: "houzi", text: "猴子", aliases: ["猴子", "猴", "houzi", "hauzi"] },
    ],
  },
  {
    id: "food",
    title: "好吃的食物",
    emoji: "🍎",
    cover: "images/words/pingguo.jpg",
    words: [
      { id: "mifan", text: "米飯", aliases: ["米飯", "米饭", "飯", "白飯", "mifan", "faan", "fan"] },
      { id: "mianbao", text: "麵包", aliases: ["麵包", "面包", "mianbao", "minbaau"] },
      { id: "pingguo", text: "蘋果", aliases: ["蘋果", "苹果", "pingguo", "pinggwo"] },
      { id: "xiangjiao", text: "香蕉", aliases: ["香蕉", "xiangjiao", "hoengziu"] },
      { id: "niunai", text: "牛奶", aliases: ["牛奶", "奶", "niunai", "milk"] },
      { id: "shui", text: "水", aliases: ["水", "喝水", "shui", "seoi"] },
      { id: "jidan", text: "雞蛋", aliases: ["雞蛋", "鸡蛋", "蛋", "jidan", "gaidaan", "egg"] },
      { id: "dangao", text: "蛋糕", aliases: ["蛋糕", "dangao", "daangou", "cake"] },
    ],
  },
  {
    id: "daily",
    title: "家和學校",
    emoji: "🏫",
    cover: "images/words/xuexiao.jpg",
    words: [
      { id: "jia", text: "家", aliases: ["家", "屋企", "家裡", "家里", "jia", "ukkei", "ukkei"] },
      { id: "xuexiao", text: "學校", aliases: ["學校", "学校", "xuexiao", "hokhaau"] },
      { id: "gongyuan", text: "公園", aliases: ["公園", "公园", "gongyuan", "gungjyun"] },
      { id: "shu", text: "書", aliases: ["書", "书", "圖書", "shu", "syu"] },
      { id: "qiu", text: "球", aliases: ["球", "皮球", "qiu", "kau"] },
      { id: "che", text: "車", aliases: ["車", "车", "汽車", "che", "ce"] },
      { id: "yifu", text: "衣服", aliases: ["衣服", "衫", "yifu", "saam"] },
      { id: "xiezi", text: "鞋子", aliases: ["鞋子", "鞋", "xiezi", "haai"] },
    ],
  },
];
